"""empty message

Revision ID: 06ac8572eede
Revises: 657d261ae15f
Create Date: 2020-06-18 18:06:34.377386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ac8572eede'
down_revision = '657d261ae15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('bought', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'item', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'bought')
    # ### end Alembic commands ###
