"""empty message

Revision ID: 0e6a907edfeb
Revises: 2d54643bc2c5
Create Date: 2020-06-03 15:40:56.071133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6a907edfeb'
down_revision = '2d54643bc2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_list', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'item_list', type_='foreignkey')
    op.create_foreign_key(None, 'item_list', 'user', ['owner_id'], ['id'])
    op.drop_column('item_list', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_list', sa.Column('owner', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'item_list', type_='foreignkey')
    op.create_foreign_key(None, 'item_list', 'user', ['owner'], ['id'])
    op.drop_column('item_list', 'owner_id')
    # ### end Alembic commands ###
