"""empty message

Revision ID: 657d261ae15f
Revises: 3f29be0e0f54
Create Date: 2020-06-18 17:40:46.315940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657d261ae15f'
down_revision = '3f29be0e0f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('item', sa.Column('category', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'category', ['category'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'category')
    op.drop_table('category')
    # ### end Alembic commands ###
