"""empty message

Revision ID: d84aed6fb59d
Revises: 2d2f5730e25b
Create Date: 2020-06-04 10:03:50.731830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84aed6fb59d'
down_revision = '2d2f5730e25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_list', type_='foreignkey')
    op.create_foreign_key(None, 'item_list', 'user', ['owner_id'], ['id'])
    op.drop_column('item_list', 'owner')
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), nullable=False))
    op.drop_column('user', 'password_hash')
    op.add_column('item_list', sa.Column('owner', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'item_list', type_='foreignkey')
    op.create_foreign_key(None, 'item_list', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###
